FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY . .

RUN chmod +x mvnw

RUN ./mvnw clean package -DskipTests -pl telegram-input-service -am

EXPOSE 8081

CMD ["java", "-jar", "telegram-input-service/target/telegram-input-service-0.3.0-SNAPSHOT.jar"]