FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY . .

RUN chmod +x mvnw

RUN ./mvnw clean package -DskipTests -pl pdf-service -am

EXPOSE 8083

CMD ["java", "-jar", "pdf-service/target/pdf-service-0.3.0-SNAPSHOT.jar"]
