FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY . .

RUN chmod +x mvnw

RUN ./mvnw clean package -DskipTests -pl health-data-service -am

EXPOSE 8080

CMD ["java", "-jar", "health-data-service/target/health-data-service-0.0.1-SNAPSHOT.jar"]