spring:
  profiles:
    active: local
server:
    port: 8081

logging:
  level:
    org.snp.Telegram.Input.Service: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG