spring:
  config:
    import: classpath:messages.yaml
  profiles:
    group:
      prod: prod
      local: local
      sleep: sleep

logging:
  level:
    org.snp.Telegram.Input.Service: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.apache.http: INFO
pressure:
  limits:
    min-sys: 40
    max-sys: 300
    min-dia: 30
    max-dia: 200
    min-pulse: 20
    max-pulse: 300