spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 20000

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
    com.zaxxer.hikari: DEBUG

#database settings
custom:
  database:
    schema: health
    tables:
      users: users
      pressure_records: pressure_records