spring:
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

#database settings
custom:
  database:
    schema: health
    tables:
      users: users
      pressure_records: pressure_records